### ISSUE TITLE
Add this to the latest package set

### ISSUE THREAD

**Issue by Eugleo** [artemisSystem/purescript-canvas-action#3]
Hey, I've build `purescript-grid-reactors` with this library, however I'm unable to add it to the package set, because `canvas-action` isn't there, either. Any plans on adding it? Is there anything _I_ can do to help?

**Comment by artemisSystem** [comment]
Oh, right. I was going to do this, but never got to it. If you want to, you can add it yourself, at the same time as adding `grid-reactors`. Just open a PR adding both. If you're unsure how to, just ask in the purescript discord and I or someone else can probably help you. Otherwise i could probably add it myself in a bit.

**Comment by Eugleo** [comment]
I’ll get to it tomorrow. If you manage to do it before then, let me know.
